# Generated by Django 4.2.4 on 2023-08-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Title Article')),
                ('anons', models.CharField(max_length=250, verbose_name='Description')),
                ('full_text', models.TextField(verbose_name='Description')),
                ('date', models.DateTimeField(verbose_name='Date publication')),
            ],
        ),
    ]
